//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deadline.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectsRequirements
    {
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public int EmployeeTypeId { get; set; }
        public int EmployeesNumber { get; set; }
    
        public virtual EmployeesTypes EmployeesTypes { get; set; }
        public virtual Projects Projects { get; set; }
    }
}
